# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Nishant Bansal
tagline:          'My dot on the web'
description:      ''
url:              https://nishantbansal.in/
baseurl:          ""

paginate:         5

# Custom vars
version:          2.1.0

# Gems
gems: [jekyll-paginate]
